### ISSUE TITLE
The Maintaince Question

### ISSUE THREAD

**Issue by machiav3lli** [farmerbb/libtaskbar#1]
At first, thanks for the nice project. Secondly as the project seems to be playing a secondary role for you, the question came up if you're planning to maintain it further or it'll be (or is already) dumped?

**Comment by farmerbb** [comment]
Thanks for reaching out. libtaskbar is updated at the same time as the main Taskbar app is updated, as they are built from the same codebase. This repo is just for the build script, plus a demo application. I am currently working on an update to the Taskbar app which will be released in the next few weeks, once that is released I will push out an update to libtaskbar at the same time.

**Comment by machiav3lli** [comment]
Oh, that's really nice to hear. Thank you.

**Comment by farmerbb** [comment]
libtaskbar 2.2.0 has now been published.

**Comment by machiav3lli** [comment]
Cool thanks!

**Comment by farmerbb** [comment]
Sorry about that, ran into some JitPack publishing issues with 2.2.0.  The artifact is properly built now, so it should be ready for you to use.
