### ISSUE TITLE
[Issue] targetSDK 31: Manifest merger fails

### ISSUE THREAD

**Issue by machiav3lli** [farmerbb/libtaskbar#2]
While trying to raise targetSDK of Omega, we have faced the error message:

`Manifest merger failed : android:exported needs to be explicitly specified for <activity>...`

And after long researching and digging for the reason(s), it seems that the manifest part of the libTaskbar (gets merged to the other projects' manifests) is missing the attribute in each single component.

Solving this should be relatively easy through adding `android:exported="true/false"` to each component.

Tell me if I can help out on this. Cheers!

**Comment by farmerbb** [comment]
Thanks for bringing this to my attention. I've been meaning to get a new release of Taskbar / libtaskbar out anyway, I'll get this done by this weekend.

Does libtaskbar need to target API 31 as well?  I was planning on staying on 30 for now, but should be able to bump it up to 31 if needed.

**Comment by farmerbb** [comment]
This should now be fixed for the next release, which I'm still hoping to get out by the end of the weekend.
